services:
  - type: web
    name: musictransfer
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://music-transfer-backend.onrender.com
    buildFilter:
      paths:
        - frontend/**/*
    disk:
      name: next-cache
      mountPath: /opt/render/project/src/frontend/.next/cache
      sizeGB: 1

  - type: web
    name: music-transfer-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python script.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: redis
    name: music-transfer-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: starter